### ISSUE TITLE
'require' does not work

### ISSUE THREAD

**Issue by MichaelJHla** [MichaelJHla/Rivernet#11]
The require method causes the error 'Uncaught ReferenceError: require is not defined' so data cannot be submitted

**Comment by Risauce** [comment]
It's so strange that require doesn't work, it is the ES5 way to import things. I am working on the Node.js project to get this stuff to work in "fullRestart" branch. It is almost complete

**Comment by Risauce** [comment]
The branch is working perfectly on my machine. Now we must test it in Firebase to ensure that it works fully. Once that is done this issue is complete!
