### ISSUE TITLE
Only one item can be changed at a time on the edit screen

### ISSUE THREAD

**Issue by MichaelJHla** [MichaelJHla/Rivernet#17]
Currently, only one change the user makes on the edit screen is applied at a time. So if the user wants to change to values on the edit screen they must do one edit at a time and submit the edit after each change. Proper functionality would mean that any number of fields can be changed and all of the changed will be applied at once.

**Comment by Risauce** [comment]
I think this is fixed right?

**Comment by MichaelJHla** [comment]
Before fully closing the bug I am just making sure that the bug does not occur for a few other examples I am going to try, but so far it seems to be fixed.
