### ISSUE TITLE
Travis not Completed

### ISSUE THREAD

**Issue by Risauce** [MichaelJHla/Rivernet#2]
As the project is currently configured Travis only automatically lints the code. There are no Unit tests to test our functions (specifically need to test _funtion submit()_. 

We could also set up Travis to auto deploy to Firebase once a build is successful. This article is the process of setting up the Firebase auto deployment: https://docs.travis-ci.com/user/deployment/firebase/

**Comment by annajinneman** [comment]
Is this something I should try to fix or will it only be possible to resolve with admin Firebase privileges?

**Comment by Risauce** [comment]
Unit tests are in! Of course we only have one function for Unit testing so we will need to add more. I'm going to work on adding Integration and E2E testing now.

**Comment by Risauce** [comment]
Travis now has email notifications set up if a build fails on dev branch. It also notifies everyone (but Jonah atm need his email) whenever there is a push (or most likely a merge) into master.

**Comment by Risauce** [comment]
Turns out travis can only auto-deploy to production (which seems very strange) but I did create a system that allows you to manually deploy to a dev/staging webapp. Going to close this issue.
