### ISSUE TITLE
Correct Class Diagram Draft?

### ISSUE THREAD

**Issue by annajinneman** [MichaelJHla/Rivernet#3]
Is this the correct outline for the RiverNET beta release? There aren't any "classes" this seemed the most logical way to make the diagram, but I'm not sure if its correct. 

![classDiagram](https://user-images.githubusercontent.com/42879603/75948620-35763780-5e61-11ea-8646-7fde6a6c858f.jpeg)

**Comment by MichaelJHla** [comment]
This is what I am probably going to make mine look like. I am hoping to have one finished by tomorrow, but I imaging this will do just fine for the beta release until our project becomes more complex on the JS side of things

**Comment by annajinneman** [comment]
You don't need to make one! I'll finish this up and add it to the documentation!
